CREATE DATABASE Down;

USE Down;

CREATE TABLE UserTable(
	id INT PRIMARY KEY AUTOINCREMENT NOT NULL,
	username VARCHAR(20) UNIQUE,
	pwd VARCHAR(100),
	email VARCHAR(100),
	create_on DATETIME NOT NULL DEFAULT NOW()
);
